# 数据源配置
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            # 主库数据源
            jdbc-url: jdbc:mysql://localhost:3306/ry_vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: root
            password: 104919
            # 初始连接数
            minimum-idle: 5
            # 最大连接池数量
            maximum-pool-size: 20
            # 连接超时时间（毫秒）
            connection-timeout: 30000
            # 空闲连接超时时间（毫秒）
            idle-timeout: 600000
            # 注册超时时间（毫秒）
            registration-timeout: 30000
            # 连接验证查询
            connection-test-query: SELECT 1
            # 监控
            register-mbeans: false
